name: CI - Build Swiggy Docker Images

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1ï¸âƒ£ Checkout Code
    - name: Checkout Source Code
      uses: actions/checkout@v3

    # 2ï¸âƒ£ Login to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 3ï¸âƒ£ Setup Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 4ï¸âƒ£ Build & Push Backend
    - name: Build & Push Backend Image
      run: |
        docker build -t mdaqib/swiggy-backend:latest -f proxy-server/Dockerfile.backend proxy-server
        docker push mdaqib/swiggy-backend:latest

    # 5ï¸âƒ£ Build & Push Frontend
    - name: Build & Push Frontend Image
      run: |
        docker build -t mdaqib/swiggy-frontend:latest -f Dockerfile.frontend .
        docker push mdaqib/swiggy-frontend:latest

    - name: Build Completed
      run: echo "ðŸš€ Docker Images Build & Push Done Successfully!"

    # 6ï¸âƒ£ ðŸ”¥ Deploy to EC2 (Auto Update)
    - name: Deploy to EC2
      run: |
        echo "${{ secrets.EC2_KEY }}" > key.pem
        chmod 600 key.pem
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "bash ~/deploy.sh"
